require 'plugins.treesitter'
require 'plugins.lualine'
require 'plugins.bufferline'
require 'plugins.nvim-tree'
require 'plugins.autopairs'
require 'plugins.which-key'
require 'plugins.telescope'
require 'plugins.lsp'
require 'plugins.colorizer'
require 'plugins.gitsigns'
require 'plugins.dashboard'
require 'plugins.indent-blankline'
require 'plugins.formatter'
require 'plugins.comment'
require 'plugins.toggleterm'
require 'plugins.lspsaga'

